### ISSUE TITLE
`Wait()` deadlocks after `Kill()` if `Go()` has never been called

### ISSUE THREAD

**Issue by olivercalder** [go-tomb/tomb#30]
If the following occurs:

1. a tomb is declared
2. the `Kill()` method is called on it (without having first called `Go()`)
3. the `Wait()` method is called

then a deadlock occurs, as `Wait()` is waiting for the `dead` channel to be closed, which is done by the final terminating goroutine, which in this case have never been created.

As a result, a later call to `Go()` does *not* result in a runtime panic, like the documentation could be interpreted to suggest it should:

> Calling the Go method after all tracked goroutines return causes a runtime panic.

Similarly, the documentation for `Wait()`:

> Wait blocks until all goroutines have finished running, and then returns the reason for their death.

could also be interpreted to mean a deadlock should not occur, as it is vacuously true that "all goroutines have finished running" if no goroutines were started in the first place.

See the following code snippet:
```go
	var t tomb.Tomb
	t.Kill(errors.New("foo"))
	t.Go(func() error {
		time.Sleep(time.Second)
		fmt.Println("I'm alive")
		return errors.New("shouldn't have happened")
	})
	fmt.Printf("Received from dead tomb: %v\n", t.Wait())
```

Here are some ready-made Go Playground examples:
- `Go()` does not panic after `Kill()`: https://play.golang.com/p/OTCEGDTVnj0
- `Wait()` deadlocks if `Go()` never called: https://play.golang.com/p/D_KTqSJuJQ_O

This is either a convenient feature (guarantee that first `Go()` call will not panic), or a bug (inconsistent behavior of `Wait()` depending on whether `Go()` has previously been called).

I'm inclined to favor the former, as I think it makes tombs safer to use in most cases. It is a problem if one assumes (as I did) that `Wait()` will not deadlock if no tracked goroutines have been created. I think the documentation for `Go()`, `Wait()`, and `Dead()` could to be updated to make this a bit clearer to users. What do you think about this?

**Comment by niemeyer** [comment]
Hi Oliver,

First, thanks for the careful bug report. I wish these were always so clear and organized.

>then a deadlock occurs, as Wait() is waiting for the dead channel to be closed, which is done by the final terminating goroutine, which in this case have never been created.
(...)
>This is either a convenient feature (guarantee that first Go() call will not panic), 

This is not just a convenience, but rather a key design aspect that cannot change without introducing major bugs, or even making the package somewhat pointless. Kill is a polite request for the Go methods to stop, not an order, and clearly given the point of the package it may be called from any goroutine. That's also why we have a distinction between Dying and Dead. So the suggestion that calling Kill would be equivalent to terminating the Tomb even though the Go method was not _yet_ called would mean that there would be an unavoidable race between Go and Kill which could cause a panic based on timing alone. Also, it would mean required logic inside the goroutine would run or not based on external conditions, so we couldn't delegate any work that _must_ run to the goroutine, which again is a good reason why the package exists.

I'm happy to see docs updated if we find a clear way to state this, but the only thing it must say is don't hand a tomb out if you don't intend on running a goroutine with it. That's the whole point of this package.
